[build]
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 5173

[build.environment]
  NETLIFY_USE_YARN = "true"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
[build]
  command = "npm run build"
  publish = "build"
 
[dev]
 command = npm run dev
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"